/**
 * Nexus Assistant - Public Version (No Auth)
 */

// UI Registry
const UI = {
    queryInput: document.getElementById('query-input'),
    resultsSection: document.getElementById('results-section'),
    emptyState: document.getElementById('empty-state'),
    searchBtn: document.getElementById('search-button'),
    btnText: document.getElementById('btn-text'),
    btnLoader: document.getElementById('btn-loader')
};

// --- Query Logic ---

async function handleQuery() {
    const query = UI.queryInput.value.trim();
    if (!query) return;

    setLoading(true);
    UI.emptyState.classList.add('hidden');
    UI.resultsSection.innerHTML = ""; // Clear previous results
    showSkeleton();

    // No Bearer token needed for public access
    const result = await API.post('/query', { input: query });

    hideSkeleton();
    setLoading(false);

    if (result.status === "success") {
        UI.queryInput.value = ""; // Clear the input field
        renderResult(result);
    } else {
        showError(result.data || "An error occurred");
    }
}

function setLoading(active) {
    UI.btnText.innerText = active ? 'Reasoning...' : 'Search';
    UI.btnLoader.classList.toggle('hidden', !active);
    UI.searchBtn.disabled = active;
}

// --- UI Polish ---

function showSkeleton() {
    const skeleton = document.createElement('div');
    skeleton.id = "query-skeleton";
    skeleton.className = "col-span-1 md:col-span-3 glass-panel p-8 space-y-4 animate-pulse mb-6";
    skeleton.innerHTML = `
        <div class="flex items-center gap-3">
            <div class="w-10 h-10 rounded-full bg-white/10"></div>
            <div class="h-4 w-32 bg-white/10 rounded"></div>
        </div>
        <div class="h-4 w-full bg-white/10 rounded"></div>
        <div class="h-4 w-5/6 bg-white/10 rounded"></div>
    `;
    UI.resultsSection.prepend(skeleton);
}

function hideSkeleton() {
    const skeleton = document.getElementById('query-skeleton');
    if (skeleton) skeleton.remove();
}

function renderResult(result) {
    const card = document.createElement('div');
    card.className = "col-span-1 md:col-span-3 glass-panel p-8 animate-entrance glow-on-hover mb-6";
    
    card.innerHTML = `
        <div class="flex items-center justify-between mb-6">
            <div class="flex items-center gap-3">
                <div class="w-12 h-12 rounded-2xl bg-indigo-500/20 flex items-center justify-center text-2xl float-icon">🧠</div>
                <div>
                    <h3 class="font-bold text-white">Nexus Intelligence</h3>
                    <p class="text-[10px] text-gray-500 uppercase tracking-widest text-indigo-400">Public Engine</p>
                </div>
            </div>
            <div class="text-[10px] px-3 py-1 rounded-full border border-white/10 text-gray-400 bg-white/5">
                ${result.metadata.cached ? '⚡ Cached Result' : '🌐 Fresh Insight'}
            </div>
        </div>
        
        <div class="text-gray-200 leading-relaxed text-lg whitespace-pre-wrap">${result.data}</div>
        
        <div class="mt-8 pt-4 border-t border-white/5 flex justify-between items-center text-[10px] text-gray-500">
            <div class="flex gap-4">
                <span>Latency: ${result.metadata.execution_time}</span>
            </div>
            <div class="text-indigo-400 font-bold">Generated by Llama-3 (Groq)</div>
        </div>
    `;

    UI.resultsSection.prepend(card);
}

function showError(msg) {
    const err = document.createElement('div');
    err.className = "col-span-1 md:col-span-3 border border-red-500/30 bg-red-500/5 text-red-400 p-4 rounded-xl text-sm animate-entrance mb-4";
    err.innerText = `⚠️ ${msg}`;
    UI.resultsSection.prepend(err);
    setTimeout(() => err.remove(), 5000);
}

UI.queryInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') handleQuery();
});
